name: Run gengxin1.py Daily

on:
  schedule:
    # 每周一到周五 15:30 德国时间启动
    # 注意 UTC 时间：冬令时 CET(UTC+1) -> 14:30 UTC
    #           夏令时 CEST(UTC+2) -> 13:30 UTC
    - cron: '13 13 * * 1-5'
  workflow_dispatch:  # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run gengxin1.py
        run: |
          python gengxin1.py
